### ISSUE TITLE
Serverless package doesn't work with serverless-plugin-warmup

### ISSUE THREAD

**Issue by JulioC** [Bielik20/nx-plugins#101]
When running `@ns3/nx-serverless:sls` executor with `package` command, it fails if the `serverless.yml` is using `serverless-plugin-warmup`. 

To reproduce this issue, generate an app using `npx nx generate @ns3/nx-serverless:app my-app-name --plugin @ns3/nx-serverless/plugin`, install the dependency `serverless-plugin-warmup@^8.2.1` and modify the `serverless.yml` follow as described below:

```yml
service: my-app-name

plugins:
  - '@ns3/nx-serverless/plugin'
  - serverless-offline
  # Declare the plugin
  - serverless-plugin-warmup

# ...

# Add the custom properties
custom:
  warmup:
    default:
      enabled: true
      prewarm: true
      events:
        - schedule: rate(4 minutes)

# ...
```

The error thrown is described below.

```
Error: Unexpected exit code from native zip: 12
 executed command 'zip --quiet --recurse-paths /my-project/packages/my-app-name/.serverless/warmUpPluginDefault.zip'
 executed in directory '/my-project/dist/packages/my-app-name'
```

It appears `@ns3/nx-serverless` ignores the warmup handler path (which is not in the dist folder), so it tried to create a zip without contents.
